export enum ROUTES {
    HOME = "/",
    SIGNIN = "/signin",
    SIGNIN_GOOGLE = "/signingoogle",
    SIGNUP = "/signup",
    ONBOARDING = "/onboarding",
    FEED = "/feed",
    BUSINESS_FEED = "/business/feed",
    WORKER_FEED = "/worker/feed",
    WORKER_JOB = '/worker/job',
    OTHER_WORKER_PROFILE = "/profile/worker",
    OTHER_BUSINESS_PROFILE = "/profile/business",
    MY_WORKER_PROFILE = "/worker/profile",
    MY_BUSINESS_PROFILE = "/business/profile",
    POST_A_JOB = "/business/post-a-job",
  }
