import type { JobsResponse } from "./types"

export const mockJobsData: JobsResponse = {
  totalCount: 6,
  totalPages: 1,
  currentPage: 1,
  hasMore: false,
  jobs: [
    {
      id: "65749f63-84d5-4bcd-b875-c40da8c6e96a",
      title: "Experienced Electrician Needed for Residential Wiring",
      description:
        "Looking for a licensed electrician to help with rewiring a residential home. Tasks include installing outlets, switches, light fixtures, and ensuring all work meets safety codes. Tools and transportation required. Project expected to last 2 weeks.",
      budget: 1500,
      hourlyRateMin: 25,
      hourlyRateMax: 40,
      businessProfileId: "02e4812a-33d4-4594-9904-65030aaadc22",
      status: "OPEN",
      createdAt: "2025-05-17T16:02:55.342Z",
      updatedAt: "2025-05-17T16:02:55.342Z",
      expiresAt: null,
      employmentType: "FULL_TIME",
      jobType: "CONTRACT",
      startDate: "2025-06-01",
      numberOfWorkersRequired: 1,
      numberOfPositions: 1,
      requirements: "Must have valid electrician license and 5+ years of experience",
      businessProfile: {
        id: "02e4812a-33d4-4594-9904-65030aaadc22",
        companyName: "Logistica",
        description:
          "Need reliable plumbing help? I'm a licensed plumber with over 5 years of experience handling everything from leak repairs and pipe installations to bathroom remodeling and emergency services. Whether it's a clogged drain or a full repiping job, I deliver fast, affordable, and high-quality work. Available for both residential and commercial projects. Satisfaction guaranteed.",
        industry: "technology",
        city: "Miami",
        state: "Florida",
        country: "United States",
        website: "https://www.linkedin.com/in/naveedalirehmani/",
        employeeCount: 6,
        yearFounded: 2025,
      },
      skills: [
        "QUALITY_CONTROL",
        "CODE_COMPLIANCE",
        "STRUCTURAL_ASSESSMENT",
        "INSTRUMENT_TECHNICIAN",
        "MAINTENANCE_TECHNICIAN",
        "ELECTRONICS_TECHNICIAN",
        "CALIBRATION_SPECIALIST",
      ],
    },
    {
      id: "b869cf47-f25b-4585-95ea-ec8355807309",
      title: "Experienced Electrician Needed for Residential Wiring",
      description:
        "Looking for a licensed electrician to help with rewiring a residential home. Tasks include installing outlets, switches, light fixtures, and ensuring all work meets safety codes. Tools and transportation required. Project expected to last 2 weeks.",
      budget: 1500,
      hourlyRateMin: 25,
      hourlyRateMax: 40,
      businessProfileId: "02e4812a-33d4-4594-9904-65030aaadc22",
      status: "OPEN",
      createdAt: "2025-05-17T16:02:54.602Z",
      updatedAt: "2025-05-17T16:02:54.602Z",
      expiresAt: null,
      employmentType: "FULL_TIME",
      jobType: "CONTRACT",
      startDate: "2025-06-01",
      numberOfWorkersRequired: 1,
      numberOfPositions: 1,
      requirements: "Must have valid electrician license and 5+ years of experience",
      businessProfile: {
        id: "02e4812a-33d4-4594-9904-65030aaadc22",
        companyName: "Logistica",
        description:
          "Need reliable plumbing help? I'm a licensed plumber with over 5 years of experience handling everything from leak repairs and pipe installations to bathroom remodeling and emergency services. Whether it's a clogged drain or a full repiping job, I deliver fast, affordable, and high-quality work. Available for both residential and commercial projects. Satisfaction guaranteed.",
        industry: "technology",
        city: "Miami",
        state: "Florida",
        country: "United States",
        website: "https://www.linkedin.com/in/naveedalirehmani/",
        employeeCount: 6,
        yearFounded: 2025,
      },
      skills: [
        "QUALITY_CONTROL",
        "CODE_COMPLIANCE",
        "STRUCTURAL_ASSESSMENT",
        "INSTRUMENT_TECHNICIAN",
        "MAINTENANCE_TECHNICIAN",
        "ELECTRONICS_TECHNICIAN",
        "CALIBRATION_SPECIALIST",
      ],
    },
    {
      id: "43a1ac2b-d944-43a8-b9dc-e7bfac63a593",
      title: "Experienced Electrician Needed for Residential Wiring",
      description:
        "Looking for a licensed electrician to help with rewiring a residential home. Tasks include installing outlets, switches, light fixtures, and ensuring all work meets safety codes. Tools and transportation required. Project expected to last 2 weeks.",
      budget: 1500,
      hourlyRateMin: 25,
      hourlyRateMax: 40,
      businessProfileId: "02e4812a-33d4-4594-9904-65030aaadc22",
      status: "OPEN",
      createdAt: "2025-05-17T16:02:53.844Z",
      updatedAt: "2025-05-17T16:02:53.844Z",
      expiresAt: null,
      employmentType: "FULL_TIME",
      jobType: "CONTRACT",
      startDate: "2025-06-01",
      numberOfWorkersRequired: 1,
      numberOfPositions: 1,
      requirements: "Must have valid electrician license and 5+ years of experience",
      businessProfile: {
        id: "02e4812a-33d4-4594-9904-65030aaadc22",
        companyName: "Logistica",
        description:
          "Need reliable plumbing help? I'm a licensed plumber with over 5 years of experience handling everything from leak repairs and pipe installations to bathroom remodeling and emergency services. Whether it's a clogged drain or a full repiping job, I deliver fast, affordable, and high-quality work. Available for both residential and commercial projects. Satisfaction guaranteed.",
        industry: "technology",
        city: "Miami",
        state: "Florida",
        country: "United States",
        website: "https://www.linkedin.com/in/naveedalirehmani/",
        employeeCount: 6,
        yearFounded: 2025,
      },
      skills: [
        "QUALITY_CONTROL",
        "CODE_COMPLIANCE",
        "STRUCTURAL_ASSESSMENT",
        "INSTRUMENT_TECHNICIAN",
        "MAINTENANCE_TECHNICIAN",
        "ELECTRONICS_TECHNICIAN",
        "CALIBRATION_SPECIALIST",
      ],
    },
    {
      id: "ecee3d25-40fc-40f0-bd96-9d81a9c435ec",
      title: "Experienced Electrician Needed for Residential Wiring",
      description:
        "Looking for a licensed electrician to help with rewiring a residential home. Tasks include installing outlets, switches, light fixtures, and ensuring all work meets safety codes. Tools and transportation required. Project expected to last 2 weeks.",
      budget: 1500,
      hourlyRateMin: 25,
      hourlyRateMax: 40,
      businessProfileId: "02e4812a-33d4-4594-9904-65030aaadc22",
      status: "OPEN",
      createdAt: "2025-05-17T16:02:52.941Z",
      updatedAt: "2025-05-17T16:02:52.941Z",
      expiresAt: null,
      employmentType: "FULL_TIME",
      jobType: "CONTRACT",
      startDate: "2025-06-01",
      numberOfWorkersRequired: 1,
      numberOfPositions: 1,
      requirements: "Must have valid electrician license and 5+ years of experience",
      businessProfile: {
        id: "02e4812a-33d4-4594-9904-65030aaadc22",
        companyName: "Logistica",
        description:
          "Need reliable plumbing help? I'm a licensed plumber with over 5 years of experience handling everything from leak repairs and pipe installations to bathroom remodeling and emergency services. Whether it's a clogged drain or a full repiping job, I deliver fast, affordable, and high-quality work. Available for both residential and commercial projects. Satisfaction guaranteed.",
        industry: "technology",
        city: "Miami",
        state: "Florida",
        country: "United States",
        website: "https://www.linkedin.com/in/naveedalirehmani/",
        employeeCount: 6,
        yearFounded: 2025,
      },
      skills: [
        "QUALITY_CONTROL",
        "CODE_COMPLIANCE",
        "STRUCTURAL_ASSESSMENT",
        "INSTRUMENT_TECHNICIAN",
        "MAINTENANCE_TECHNICIAN",
        "ELECTRONICS_TECHNICIAN",
        "CALIBRATION_SPECIALIST",
      ],
    },
    {
      id: "5c94a421-4cef-488d-bedb-814a22c8b57e",
      title: "Experienced Electrician Needed for Residential Wiring",
      description:
        "Looking for a licensed electrician to help with rewiring a residential home. Tasks include installing outlets, switches, light fixtures, and ensuring all work meets safety codes. Tools and transportation required. Project expected to last 2 weeks.",
      budget: 1500,
      hourlyRateMin: 25,
      hourlyRateMax: 40,
      businessProfileId: "02e4812a-33d4-4594-9904-65030aaadc22",
      status: "OPEN",
      createdAt: "2025-05-17T16:02:52.060Z",
      updatedAt: "2025-05-17T16:02:52.060Z",
      expiresAt: null,
      employmentType: "FULL_TIME",
      jobType: "CONTRACT",
      startDate: "2025-06-01",
      numberOfWorkersRequired: 1,
      numberOfPositions: 1,
      requirements: "Must have valid electrician license and 5+ years of experience",
      businessProfile: {
        id: "02e4812a-33d4-4594-9904-65030aaadc22",
        companyName: "Logistica",
        description:
          "Need reliable plumbing help? I'm a licensed plumber with over 5 years of experience handling everything from leak repairs and pipe installations to bathroom remodeling and emergency services. Whether it's a clogged drain or a full repiping job, I deliver fast, affordable, and high-quality work. Available for both residential and commercial projects. Satisfaction guaranteed.",
        industry: "technology",
        city: "Miami",
        state: "Florida",
        country: "United States",
        website: "https://www.linkedin.com/in/naveedalirehmani/",
        employeeCount: 6,
        yearFounded: 2025,
      },
      skills: [
        "QUALITY_CONTROL",
        "CODE_COMPLIANCE",
        "STRUCTURAL_ASSESSMENT",
        "INSTRUMENT_TECHNICIAN",
        "MAINTENANCE_TECHNICIAN",
        "ELECTRONICS_TECHNICIAN",
        "CALIBRATION_SPECIALIST",
      ],
    },
    {
      id: "b3d98e98-5430-4243-8de6-8c1066376e2d",
      title: "Experienced Electrician Needed for Residential Wiring",
      description:
        "Looking for a licensed electrician to help with rewiring a residential home. Tasks include installing outlets, switches, light fixtures, and ensuring all work meets safety codes. Tools and transportation required. Project expected to last 2 weeks.",
      budget: 1500,
      hourlyRateMin: 25,
      hourlyRateMax: 40,
      businessProfileId: "02e4812a-33d4-4594-9904-65030aaadc22",
      status: "OPEN",
      createdAt: "2025-05-17T16:02:47.665Z",
      updatedAt: "2025-05-17T16:02:47.665Z",
      expiresAt: null,
      employmentType: "FULL_TIME",
      jobType: "CONTRACT",
      startDate: "2025-06-01",
      numberOfWorkersRequired: 1,
      numberOfPositions: 1,
      requirements: "Must have valid electrician license and 5+ years of experience",
      businessProfile: {
        id: "02e4812a-33d4-4594-9904-65030aaadc22",
        companyName: "Logistica",
        description:
          "Need reliable plumbing help? I'm a licensed plumber with over 5 years of experience handling everything from leak repairs and pipe installations to bathroom remodeling and emergency services. Whether it's a clogged drain or a full repiping job, I deliver fast, affordable, and high-quality work. Available for both residential and commercial projects. Satisfaction guaranteed.",
        industry: "technology",
        city: "Miami",
        state: "Florida",
        country: "United States",
        website: "https://www.linkedin.com/in/naveedalirehmani/",
        employeeCount: 6,
        yearFounded: 2025,
      },
      skills: [
        "QUALITY_CONTROL",
        "CODE_COMPLIANCE",
        "STRUCTURAL_ASSESSMENT",
        "INSTRUMENT_TECHNICIAN",
        "MAINTENANCE_TECHNICIAN",
        "ELECTRONICS_TECHNICIAN",
        "CALIBRATION_SPECIALIST",
      ],
    },
  ],
}
