export const API_ROUTES = {
  AUTH: {
    SIGN_UP: "/auth/sign-up",
    SIGN_IN: "/auth/sign-in",
    SIGN_OUT: "/auth/logout",
    CURRENT_USER: "/auth/me",
    GOOGLE_AUTH: "/auth/google",
    REFRESH: "/auth/refresh",
    RESET_PASSWORD: "/auth/reset-password",
    DELETE_ACCOUNT: "/auth/delete-account",
    PASSWORD_RECOVERY: "/auth/password-recovery",
    IS_AUTHENTICATED: "/auth/is-authenticated",
    LOGOUT: "/auth/logout",
    OAUTH: {
      GOOGLE: "/auth/google",
      GOOGLE_CALLBACK: "/auth/google/callback",
    },
  },
  USER: {
    BY_ID: (id: string) => `/user/${id}`,
    UPDATE_BUSINESS_PROFILE: "/user/update-business-profile",
    UPDATE_USER: "/user/update-user",
    GET_USER: "/user/me",
    TOGGLE_FIRST_TIME_LOGIN: "/user/toggle-first-time-login",
    GET_CURRENT_USER: "/user/current-user",
    DELETE_ACCOUNT: "/user/delete-account",
    FORGOT_PASSWORD: "/user/forgot-password",
    VERIFY_OTP: "/user/verify-otp",
    RESET_PASSWORD: "/user/reset-password",
    WORKER_PROFILE_DETAILS: "/user/worker-profile-details",
    
  },
  OTP: {
    SEND: "/otp/send-otp",
    VERIFY: "/otp/verify-otp",
  },
  ROLES: {
    UPDATE: (id: string) => `/roles/${id}`,
  },
  RESTRICTIONS: {
    ROOT: "/restrictions/",
    USER_RESTRICTIONS: (userId: string) => `/restrictions/${userId}`,
  },
  HEALTH: "/health",
  SUBSCRIPTION: "/subscription",
  SKILLS: {
    ROOT: "/skills",
    BY_ID: (id: string) => `/skills/${id}`,
    CREATE: "/skills",
    UPDATE: "/skills",
    DELETE: (id: string) => `/skills/${id}`,
    LIST: "/skills",
  },
  EXPERIENCE: {
    BY_ID: (id: string) => `/experience/${id}`,
    CREATE: "/experience",
    UPDATE_ALL: "/experience/update-all",
    UPDATE: (id: string) => `/experience/${id}`,
    DELETE: (id: string) => `/experience/${id}`,
    LIST: "/experience",
  },
  EDUCATION: {
    BY_ID: (id: string) => `/education/${id}`,
    CREATE: "/education",
    UPDATE: (id: string) => `/education/${id}`,
    DELETE: (id: string) => `/education/${id}`,
    LIST: "/education",
    UPDATE_ALL: "/education/update-all",
  },
  LANGUAGE: {
    CREATE: "/language/create",
    UPDATE: "/language/update",
    DELETE: "/language/delete",
    UPDATE_ALL: "/language/update-all",
  },
  WORKER: {
    UPDATE_WORKER_PROFILE: "/worker/update-worker-profile",
    ROOT: "/worker",
    BY_ID: (id: string) => `/worker/${id}`,
    LIST: "/worker/get-all-workers-profiles",
  },
  JOB: {
    ROOT: "/jobs",
    CREATE: "/jobs/create",
    UPDATE: "/jobs/update",
    DELETE: "/jobs/delete",
    LIST: "/jobs/get-all-jobs",
  },
};
