export enum ModalType {
  NONE = "NONE",
  UPGRADE = "UPGRADE",
  EDIT_PROFILE = "EDIT_PROFILE",
  EDIT_SKILLS = "EDIT_SKILLS",
  EDIT_EXPERIENCE = "EDIT_EXPERIENCE",
  EDIT_EDUCATION = "EDIT_EDUCATION",
  EDIT_LANGUAGES = "EDIT_LANGUAGES",
  EDIT_BUSINESS_PROFILE = 'EDIT_BUSINESS_PROFILE',
  EDIT_BUSINESS_ABOUT = 'EDIT_BUSINESS_ABOUT',
  EDIT_BUSINESS_SERVICES = 'EDIT_BUSINESS_SERVICES',
  EDIT_PROFILE_IMAGE = 'EDIT_PROFILE_IMAGE',
}