export enum ModalType {
  NONE = 'NONE',
  EDIT_LESSON_PLAN = 'EDIT_LESSON_PLAN',
  UPGRADE = 'UPGRADE',
  EDIT_PROFILE = 'EDIT_PROFILE',
  EDIT_SKILLS = 'EDIT_SKILLS',
  EDIT_EXPERIENCE = 'EDIT_EXPERIENCE',
  EDIT_EDUCATION = 'EDIT_EDUCATION',
  EDIT_LANGUAGES = 'EDIT_LANGUAGES',
  EDIT_BUSINESS_PROFILE = 'EDIT_BUSINESS_PROFILE',
  EDIT_BUSINESS_ABOUT = 'EDIT_BUSINESS_ABOUT',
  EDIT_BUSINESS_SERVICES = 'EDIT_BUSINESS_SERVICES',
  EDIT_PROFILE_IMAGE = 'EDIT_PROFILE_IMAGE',
  UPLOAD_LOGO = 'UPLOAD_LOGO'
  // Add more modal types here as needed
}
