export enum ModalType {
    NONE = "NONE",
    EDIT_LESSON_PLAN = "EDIT_LESSON_PLAN",
    UPGRADE = "UPGRADE",
    EDIT_PROFILE = "EDIT_PROFILE",
    EDIT_SKILLS = "EDIT_SKILLS",
    EDIT_EXPERIENCE = "EDIT_EXPERIENCE",
    EDIT_EDUCATION = "EDIT_EDUCATION",
    EDIT_LANGUAGES = "EDIT_LANGUAGES",
    CHANGE_PROFILE_PICTURE = "CHANGE_PROFILE_PICTURE",
    // Add more modal types here as needed
  } 