export enum QueryKeys {
  AUTH = "auth",
  SIGN_UP = "sign-up",
  SIGN_IN = "sign-in",
  SIGN_OUT = "sign-out",
  CURRENT_USER = "current-user",
  USERS = "users",
  UPDATE_USER = "update-user",
  GET_USER = "get-user",
  USER = "user",
  UPDATE_WORKER_PROFILE = "update-worker-profile",
  UPDATE_BUSINESS_PROFILE = "update-business-profile",
  GET_SKILLS = "get-skills",
  GET_EXPERIENCE = "get-experience",
  GET_EDUCATIONS = "educations",
  CREATE_SKILLS = "create-skills",
  CREATE_LANGUAGES = "create-languages",
  CREATE_EDUCATIONS = "create-educations",
  UPDATE_EDUCATIONS = "update-educations",
  DELETE_EDUCATIONS = "delete-educations",
  GET_WORKERS = "get-workers",
  GET_WORKER_PROFILE = "get-worker-profile",
  GET_WORKER_BY_ID = "get-worker-by-id",
  LOGOUT = "logout",
}
